import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { loadManifest } from "./validate-modules.mjs";

export function renderRegistration(manifest) {
  const imports = manifest.modules.map(
    (module) =>
      `import { ${module.factory} } from "${module.package}";\n` +
      `import "${module.package}/${module.style}";`,
  );
  const factories = manifest.modules.map((module) => `  ${module.factory},`);
  return [
    "// Generated by scripts/generate-modules.mjs. Do not edit.",
    'import type { ApplicationModuleFactory } from "@yutakax17/advanced-hello-world-fe-core";',
    `import "${manifest.core.package}/${manifest.core.style}";`,
    ...imports,
    "",
    "export const moduleFactories: readonly ApplicationModuleFactory[] = [",
    ...factories,
    "];",
    "",
  ].join("\n");
}

async function main() {
  const check = process.argv.includes("--check");
  const manifest = await loadManifest(resolve("modules.json"));
  const outputPath = resolve("src/generated-modules.ts");
  const expected = renderRegistration(manifest);
  if (check) {
    const current = await readFile(outputPath, "utf8");
    if (current !== expected) {
      throw new Error(
        "src/generated-modules.ts is stale; run npm run modules:generate",
      );
    }
  } else {
    await writeFile(outputPath, expected);
  }
}

if (process.argv[1] && import.meta.url.endsWith(process.argv[1])) {
  main().catch((error) => {
    console.error(error.message);
    process.exitCode = 1;
  });
}
