// Generated by scripts/generate-modules.mjs. Do not edit.
import type { ApplicationModuleFactory } from "@yutakax17/advanced-hello-world-fe-core";
import "@yutakax17/advanced-hello-world-fe-core/styles.css";
import { createMessagesModule } from "@yutakax17/advanced-hello-world-fe-messages";
import "@yutakax17/advanced-hello-world-fe-messages/styles.css";

export const moduleFactories: readonly ApplicationModuleFactory[] = [
  createMessagesModule,
];
